name: CI for MWAA
on:
  push:
    branches:
      - main
env:
  BUCKET_NAME: "arn:aws:s3:::aws-ia-mwaa-339712836592"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repository
        uses: actions/checkout@main

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ env.BUCKET_NAME }}
      
      - name: Sync airflow file to MWAA S3 buckers with AWS cli
        run: |
         aws s3 sync . s3://${{ env.BUCKET_NAME }} --follow-symlinks --delete --exclude '.git/*'
